name: Deploy to VSB Server

on:
  push:

    branches: [ "main", "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Create ZIP archive
        run: zip -r ${{ secrets.VSB_USERNAME }}.zip . -x ".git/*" ".github/*"

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VSB_HOST }}
          username: ${{ secrets.VSB_USERNAME }}
          password: ${{ secrets.VSB_PASSWORD }}
          port: 22
          target: "~/public_html"
          source: ".,!*.git*,!*.github*"
          overwrite: true
